[colors.primary]
background = "#282828"
foreground = "#a6a28c"

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[cursor.style]
shape = "Beam"

[colors.cursor]
cursor = "#a6a28c"
text = "#20201d"

[font]
size = 14

[font.normal]
family = "SauceCodePro Nerd Font"

[scrolling]
history = 0

[window]
decorations = "none"
