theme = "zdarker"

[editor]
color-modes = true
bufferline = "multiple"
cursorline = true
cursorcolumn = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "underline"
normal = "block"

[editor.statusline]
left = ["mode", "spacer", "spinner", "file-name", "file-encoding", "version-control"]
right = ["version-control", "diagnostics", "position", "total-line-numbers", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"left" = "no_op"
"right" = "no_op"
"up" = "no_op"
"down" = "no_op"
