theme = "zmine"

[editor]
mouse = false
color-modes = true
bufferline = "multiple"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "underline"
normal = "block"

[editor.statusline]
left = ["mode", "spacer", "spinner", "file-name"]
right = ["diagnostics", "position", "total-line-numbers", "file-line-ending", "file-type"]
separator = "   "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"left" = "no_op"
"right" = "no_op"
"up" = "no_op"
"down" = "no_op"
